name = "income-outcome-api-proxy"
main = "src/index.js"
compatibility_date = "2026-06-02"

[vars]
APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycby8X78WXQTlksxBxM2C2mWqgEUul7sukt0oZ3rBDwagBpnJQmt23gexZrNzq-0wTguM/exec"
